CC = gcc
PROGRAM_TARGET = program
PROGRAM_SOURCE = $(PROGRAM_TARGET).c

all:
	$(CC) -o $(PROGRAM_TARGET) $(PROGRAM_SOURCE) 
	#-I/usr/local/include/ -L/usr/local/lib/
	#-lavformat -lavcodec

clean:
	rm $(PROGRAM_TARGET)

