FROM ubuntu:18.04

RUN apt -y update && apt -y upgrade
RUN apt -y install \
    ffmpeg \
    sudo \
    vim \
    cmake \
    make \
    gcc \
    build-essential \
    pkg-config \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \
    libswscale-dev \
    libswresample-dev \
    libz-dev

ENV LANG en_US.UTF-8

