FROM ubuntu:18.04

RUN apt -y update && apt -y upgrade
RUN apt -y install \
    ffmpeg \
    sudo \
    vim \
    make \
    gcc \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \
    libswscale-dev \
    libz-dev

ENV LANG en_US.UTF-8

